export const globalStyles = {
  flex1: { display: 'flex', flex: 1 },
  alignCenter: { alignItems: 'center', display: 'flex' },
  justifyCenter: { justifyContent: 'center', display: 'flex' },
  flexRow: { display: 'flex', flexDirection: 'row' },
  flexCol: { display: 'flex', flexDirection: 'column' },
  padding8: { padding: 8 },
  padding16: { padding: 16 },
  margin8: { margin: 8 },
  margin16: { margin: 16 },
  marginBottom8: { marginBottom: 8 },
  marginBottom16: { marginBottom: 16 },
  marginTop8: { marginTop: 8 },
  marginTop16: { marginTop: 16 },
  font12: { fontSize: 12 },
  font14: { fontSize: 14 },
  font16: { fontSize: 16 },
  fontBold: { fontWeight: 'bold' },
  colorWhite: { color: '#fff' },
  colorRed: { color: 'red' },
  colorText: { color: '#333' },
  borderRadius8: { borderRadius: 8 },
  borderRadius16: { borderRadius: 16 },
  borderGray: { border: '1px solid #ddd' },
  bgWhite: { backgroundColor: '#fff' },
  bgGray: { backgroundColor: '#f3f4f6' },
  bgPrimary: { backgroundColor: '#c084fc' },
  centered: { display: 'flex', flex: 1, justifyContent: 'center', alignItems: 'center' },
  container: { display: 'flex', flex: 1, padding: 16 },
  content: { display: 'flex', flex: 1, padding: 16 },
  addButton: { backgroundColor: '#c084fc', padding: 12, borderRadius: 8, alignItems: 'center', marginTop: 16, color: '#fff', fontWeight: 'bold', fontSize: 16, border: 'none', cursor: 'pointer' },
  addButtonText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  section: { marginBottom: 24, padding: 16, backgroundColor: '#fff', borderRadius: 8 },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 12 },
  buttonText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  imageGrid: { display: 'flex', flexDirection: 'row', flexWrap: 'wrap', gap: 8, margin: '8px 0' },
  imageContainer: { width: 80, height: 80, margin: 4, borderRadius: 8, overflow: 'hidden', position: 'relative' },
  image: { width: '100%', height: '100%', borderRadius: 8, objectFit: 'cover' },
  removeButton: { position: 'absolute', top: 4, right: 4, backgroundColor: '#e57373', borderRadius: 12, padding: 2, color: '#fff', border: 'none', cursor: 'pointer' },
  nextButton: { backgroundColor: '#4caf50', padding: 12, borderRadius: 8, alignItems: 'center', marginTop: 16, color: '#fff', fontWeight: 'bold', fontSize: 16, border: 'none', cursor: 'pointer' },
  nextButtonText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  stepperNav: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between', marginTop: 24 },
  stepperNavText: { color: '#c084fc', fontWeight: 'bold', fontSize: 16 },
  stepperHeader: { display: 'flex', flexDirection: 'row', justifyContent: 'center', marginBottom: 16 },
  stepperDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#e0e0e0', margin: '0 4px' },
  stepperDotActive: { backgroundColor: '#c084fc' },
  scrollContent: { paddingBottom: 120 },
  saveBar: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between', padding: 16, backgroundColor: '#fff', borderTop: '1px solid #eee' },
  saveButton: { backgroundColor: '#c084fc', padding: 12, borderRadius: 8, alignItems: 'center', flex: 1, margin: '0 4px', color: '#fff', fontWeight: 'bold', fontSize: 16, border: 'none', cursor: 'pointer' },
  saveButtonText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  imagePreviewContainer: { margin: '8px 0', alignItems: 'center', display: 'flex' },
  picker: { color: '#333', backgroundColor: '#f3f4f6', borderRadius: 8, padding: 8 },
  input: { backgroundColor: '#f3f4f6', borderRadius: 8, padding: 12, marginBottom: 12, color: '#333', border: '1px solid #ccc' },
  textArea: { minHeight: 80, textAlign: 'start', padding: 12, borderRadius: 8, border: '1px solid #ccc', color: '#333' },
  text: { color: '#333', fontSize: 16 },
  button: { backgroundColor: '#c084fc', padding: 12, borderRadius: 8, alignItems: 'center', margin: '8px 0', color: '#fff', fontWeight: 'bold', fontSize: 16, border: 'none', cursor: 'pointer' },
  cancelButton: { backgroundColor: '#e57373' },
  camera: { display: 'flex', flex: 1, borderRadius: 16, overflow: 'hidden' },
  buttonContainer: { display: 'flex', flexDirection: 'row', justifyContent: 'space-around', marginTop: 16 },
}; 