import { StyleSheet } from 'react-native';

export const globalStyles = StyleSheet.create({
  flex1: { flex: 1 },
  alignCenter: { alignItems: 'center' },
  justifyCenter: { justifyContent: 'center' },
  flexRow: { flexDirection: 'row' },
  flexCol: { flexDirection: 'column' },
  padding8: { padding: 8 },
  padding16: { padding: 16 },
  margin8: { margin: 8 },
  margin16: { margin: 16 },
  marginBottom8: { marginBottom: 8 },
  marginBottom16: { marginBottom: 16 },
  marginTop8: { marginTop: 8 },
  marginTop16: { marginTop: 16 },
  font12: { fontSize: 12 },
  font14: { fontSize: 14 },
  font16: { fontSize: 16 },
  fontBold: { fontWeight: 'bold' },
  colorWhite: { color: '#fff' },
  colorRed: { color: 'red' },
  colorText: { color: '#333' },
  borderRadius8: { borderRadius: 8 },
  borderRadius16: { borderRadius: 16 },
  borderGray: { borderColor: '#ddd', borderWidth: 1 },
  bgWhite: { backgroundColor: '#fff' },
  bgGray: { backgroundColor: '#f3f4f6' },
  bgPrimary: { backgroundColor: '#c084fc' },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  container: { flex: 1, padding: 16 },
  content: { flex: 1, padding: 16 },
  addButton: { backgroundColor: '#c084fc', padding: 12, borderRadius: 8, alignItems: 'center', marginTop: 16 },
  addButtonText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  section: { marginBottom: 24, padding: 16, backgroundColor: '#fff', borderRadius: 8 },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 12 },
  buttonText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  imageGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginVertical: 8 },
  imageContainer: { width: 80, height: 80, margin: 4, borderRadius: 8, overflow: 'hidden', position: 'relative' },
  image: { width: '100%', height: '100%', borderRadius: 8 },
  removeButton: { position: 'absolute', top: 4, right: 4, backgroundColor: '#e57373', borderRadius: 12, padding: 2 },
  nextButton: { backgroundColor: '#4caf50', padding: 12, borderRadius: 8, alignItems: 'center', marginTop: 16 },
  nextButtonText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  stepperNav: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 24 },
  stepperNavText: { color: '#c084fc', fontWeight: 'bold', fontSize: 16 },
  stepperHeader: { flexDirection: 'row', justifyContent: 'center', marginBottom: 16 },
  stepperDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#e0e0e0', marginHorizontal: 4 },
  stepperDotActive: { backgroundColor: '#c084fc' },
  scrollContent: { paddingBottom: 120 },
  saveBar: { flexDirection: 'row', justifyContent: 'space-between', padding: 16, backgroundColor: '#fff', borderTopWidth: 1, borderColor: '#eee' },
  saveButton: { backgroundColor: '#c084fc', padding: 12, borderRadius: 8, alignItems: 'center', flex: 1, marginHorizontal: 4 },
  saveButtonText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  imagePreviewContainer: { marginVertical: 8, alignItems: 'center' },
  picker: { color: '#333', backgroundColor: '#f3f4f6', borderRadius: 8, padding: 8 },
  input: { backgroundColor: '#f3f4f6', borderRadius: 8, padding: 12, marginBottom: 12, color: '#333' },
  textArea: { minHeight: 80, textAlignVertical: 'top' },
  text: { color: '#333', fontSize: 16 },
  button: { backgroundColor: '#c084fc', padding: 12, borderRadius: 8, alignItems: 'center', marginVertical: 8 },
  cancelButton: { backgroundColor: '#e57373' },
  camera: { flex: 1, borderRadius: 16, overflow: 'hidden' },
  buttonContainer: { flexDirection: 'row', justifyContent: 'space-around', marginTop: 16 },
}); 