name: Deploy Functions Only

on:
  push:
    branches: [ master ]
    paths:
      - 'functions/**'
  workflow_dispatch:

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install functions dependencies
      working-directory: functions
      run: npm ci --prefer-offline

    - name: Build functions
      working-directory: functions
      run: npm run build

    - name: Type-check functions
      working-directory: functions
      run: npx tsc -p tsconfig.json --noEmit

    - name: Prepare service account
      shell: bash
      run: |
        if [[ -n "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" ]]; then
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" | base64 -d > "$GITHUB_WORKSPACE/sa.json"
        else
          printf '%s' "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "$GITHUB_WORKSPACE/sa.json"
        fi

    - name: Deploy critical functions only
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
      run: |
        echo "Deploying critical functions..."
        
        # Deploy password reset function first (most critical)
        npx firebase-tools@14.16.0 deploy --only functions:sendCustomPasswordResetEmail --project props-bible-app-1c1cb --non-interactive --debug || echo "sendCustomPasswordResetEmail failed, continuing..."
        
        # Deploy Stripe functions
        npx firebase-tools@14.16.0 deploy --only functions:getPricingConfig --project props-bible-app-1c1cb --non-interactive --debug || echo "getPricingConfig failed, continuing..."
        npx firebase-tools@14.16.0 deploy --only functions:createCheckoutSession --project props-bible-app-1c1cb --non-interactive --debug || echo "createCheckoutSession failed, continuing..."
        npx firebase-tools@14.16.0 deploy --only functions:createBillingPortalSession --project props-bible-app-1c1cb --non-interactive --debug || echo "createBillingPortalSession failed, continuing..."

    - name: Verify deployment
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
      run: |
        echo "Verifying function deployment..."
        npx firebase-tools@14.16.0 functions:list --project props-bible-app-1c1cb --filter="name:sendCustomPasswordResetEmail"
