name: Deploy Firebase Functions

on:
  push:
    branches: [ master ]
    paths:
      - 'functions/**'
      - '.github/workflows/deploy-functions.yml'
  workflow_dispatch:

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install functions dependencies
      working-directory: functions
      run: npm ci

    - name: Build functions
      working-directory: functions
      run: npm run build

    - name: Type-check functions
      working-directory: functions
      run: npx tsc -p tsconfig.json --noEmit

    - name: Prepare service account file
      shell: bash
      run: |
        set -euo pipefail
        if [[ -n "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" ]]; then
          echo "Using FIREBASE_SERVICE_ACCOUNT_BASE64"
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" | base64 -d > "$GITHUB_WORKSPACE/sa.json"
        elif [[ -n "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" ]]; then
          echo "Using FIREBASE_SERVICE_ACCOUNT"
          printf '%s' "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "$GITHUB_WORKSPACE/sa.json"
        else
          echo "No service account secret set" >&2
          exit 1
        fi
        # Minimal sanity check
        jq -r .client_email "$GITHUB_WORKSPACE/sa.json" >/dev/null 2>&1 || { echo "Invalid service account JSON" >&2; exit 1; }

    - name: Deploy specific functions (safer approach)
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
      run: |
        # Deploy functions one by one to avoid conflicts
        echo "✅ Using Firebase built-in password reset system - no custom function deployment needed"
        npx firebase-tools@14.16.0 deploy --only functions:getPricingConfig --project props-bible-app-1c1cb --non-interactive --debug || echo "getPricingConfig deployment failed, continuing..."
        npx firebase-tools@14.16.0 deploy --only functions:createCheckoutSession --project props-bible-app-1c1cb --non-interactive --debug || echo "createCheckoutSession deployment failed, continuing..."
        npx firebase-tools@14.16.0 deploy --only functions:createBillingPortalSession --project props-bible-app-1c1cb --non-interactive --debug || echo "createBillingPortalSession deployment failed, continuing..."

    - name: Verify function deployment
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
      run: |
        npx firebase-tools@14.16.0 functions:list --project props-bible-app-1c1cb
