name: Staging Deployment

on:
  push:
    branches: [ develop, staging ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-and-stage:
    runs-on: ubuntu-latest
    env:
      ROLLUP_SKIP_NODEJS_NATIVE: 'true'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install web-app dependencies
      working-directory: web-app
      run: npm ci

    - name: Create staging env file
      working-directory: web-app
      shell: bash
      env:
        VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
        VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
        VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
        VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
        VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
        VITE_GOOGLE_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}
        VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
      run: |
        echo "VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY:-dummy}" >> .env
        echo "VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN:-dummy}.firebaseapp.com" >> .env
        echo "VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID:-dummy}" >> .env
        echo "VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET:-dummy}.appspot.com" >> .env
        echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID:-000000000000}" >> .env
        echo "VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID:-1:000000000000:web:0000000000000000000000}" >> .env
        echo "VITE_GOOGLE_API_KEY=${VITE_GOOGLE_API_KEY:-dummy}" >> .env
        echo "VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID:-dummy.apps.googleusercontent.com}" >> .env

    - name: Lint and type-check
      working-directory: web-app
      run: |
        npm run lint
        npx tsc -p tsconfig.json --noEmit

    - name: Build web-app
      working-directory: web-app
      run: npm run build

    - name: Run unit tests
      working-directory: web-app
      run: npm test -- --coverage --watchAll=false

    - name: Install functions dependencies
      working-directory: functions
      run: npm ci

    - name: Build and type-check functions
      working-directory: functions
      run: |
        npm run build
        npx tsc -p tsconfig.json --noEmit

    - name: Deploy to staging (if on develop branch)
      if: github.ref == 'refs/heads/develop'
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
      run: |
        # Prepare service account
        if [[ -n "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" ]]; then
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" | base64 -d > "$GITHUB_WORKSPACE/sa.json"
        else
          printf '%s' "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "$GITHUB_WORKSPACE/sa.json"
        fi
        # Deploy to staging
        npx firebase-tools@14.16.0 deploy --only hosting --project props-bible-app-1c1cb --non-interactive
