name: Basic Test

on:
  workflow_dispatch:

jobs:
  test-basic:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Check web-app package.json
      working-directory: web-app
      run: |
        echo "Checking web-app package.json..."
        cat package.json | head -10
        echo "✅ package.json exists"

    - name: Check functions package.json
      working-directory: functions
      run: |
        echo "Checking functions package.json..."
        cat package.json | head -10
        echo "✅ package.json exists"

    - name: Install web-app dependencies
      working-directory: web-app
      run: |
        echo "Installing web-app dependencies..."
        npm install
        echo "✅ Dependencies installed"

    - name: Install functions dependencies
      working-directory: functions
      run: |
        echo "Installing functions dependencies..."
        npm install
        echo "✅ Dependencies installed"

    - name: Build web-app
      working-directory: web-app
      run: |
        echo "Building web-app..."
        npm run build
        echo "✅ Build completed"

    - name: Build functions
      working-directory: functions
      run: |
        echo "Building functions..."
        npm run build
        echo "✅ Build completed"

    - name: Test completion
      run: |
        echo "🎉 All basic tests passed!"
        echo "Build process is working correctly"
